CREATE TABLE IF NOT EXISTS `bank_deposit_clean` (
  `MyUnknownColumn` int DEFAULT NULL,
  `age` int DEFAULT NULL,
  `job` text,
  `marital` text,
  `education` text,
  `default` text,
  `balance` double DEFAULT NULL,
  `housing` text,
  `loan` text,
  `contact` text,
  `day` double DEFAULT NULL,
  `month` text,
  `duration` double DEFAULT NULL,
  `campaign` double DEFAULT NULL,
  `pdays` double DEFAULT NULL,
  `previous` double DEFAULT NULL,
  `poutcome` text,
  `Bank deposit(target)` text,
  `n_marital` int DEFAULT NULL,
  `b_default` text,
  `b_housing` text,
  `b_loan` text,
  `n_poutcome` int DEFAULT NULL,
  `b_deposit` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
